version: '3'
services:
  db:
    image: postgres:11.1
    volumes:
      - ./db/postgresql/volumes:/var/lib/postgresql/data

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
